### PR TITLE
Dynamically build audio controls

### PR DESCRIPTION
**Pull request by will-hanlen**
The ```<audio>``` elements in the HTML are used in the JS to create the audio controls. Controls get placed in the same ```<div>``` as its coresponding ```<audio>``` element.

- The play/pause button is fully functional.
- The download button is fully functional and will work on any server (but not on a local machine because of CORS restrictions)
- The time stamp displays the length of the sample (lmk if this should change and display current play time as the song plays)

The background of the audio controls changes color to display progress of the song as it plays. There is no way to seek through the song. I don't think there should be (or at least with this current method) because it will interfere with the buttons.

A possible solution is to add a full seek bar to the bottom border of the audio controls.

current: 
u
alternative:
u

Another possibility is to leave the moving gray background but do not let the user seek. instead just give them an option to restart the sample.

### CODE REVIEW

**Comment by youngliencub** [comment]
So I like the first option. I think that is fine
What do you mean by the download? Are we okay? Will people be able to download fine?

**Comment by youngliencub** [comment]
I like the idea of maybe just letting them restart

**Comment by youngliencub** [comment]
Another thought I'm having now is that we should probably make it so that the audio from another sample triggers the pause button on the current sample

**Comment by will-hanlen** [comment]
> 
> 
> So I like the first option. I think that is fine
> What do you mean by the download? Are we okay? Will people be able to download fine?

Yes download is fine. It just wont work correctly until it is running on a server.

**Comment by youngliencub** [comment]
okay heard that

**Pull request merged**
